using Microsoft.SqlServer.Dac;
using Microsoft.SqlServer.Dac.Model;

namespace EFCore.SchemaSync.Conversion;

/// <summary>Builds and validates an in-memory DacFx model and DACPAC from normalized statements.</summary>
internal static class DacpacBuilder
{
    public static SchemaPackage Build(NormalizedScript script, string packageName, SqlServerVersion version, string? collation)
    {
        var modelOptions = new TSqlModelOptions { StorageType = DacSchemaModelStorageType.Memory };
        if (!string.IsNullOrWhiteSpace(collation))
        {
            modelOptions.Collation = collation;
        }

        var warnings = new List<string>(script.Warnings);

        using var model = new TSqlModel(version, modelOptions);
        foreach (var statement in script.Statements)
        {
            try
            {
                model.AddOrUpdateObjects(statement.Text, statement.SourceName, new TSqlObjectOptions());
            }
            catch (DacModelException ex)
            {
                throw new SchemaSyncException(
                    SchemaSyncStage.BuildPackage,
                    $"DacFx rejected the {statement.Kind} statement '{statement.SourceName}': {Flatten(ex.Message)}{Environment.NewLine}{statement.Text}",
                    ex);
            }
        }

        var messages = model.Validate();
        var errors = messages.Where(m => m.MessageType == DacMessageType.Error).Select(Format).ToList();
        if (errors.Count > 0)
        {
            throw new SchemaSyncException(
                SchemaSyncStage.BuildPackage,
                "The DacFx model built from the EF Core model is invalid:" + Environment.NewLine + "  - " + string.Join(Environment.NewLine + "  - ", errors));
        }

        warnings.AddRange(messages.Where(m => m.MessageType == DacMessageType.Warning).Select(Format));

        var objects = model.GetObjects(DacQueryScopes.UserDefined)
            .Where(o => o.Name.HasName)
            .Select(o => new SchemaObjectReference(o.ObjectType.Name, o.Name.ToString()))
            .ToArray();

        using var stream = new MemoryStream();
        var metadata = new PackageMetadata
        {
            Name = packageName,
            Version = "1.0.0.0",
            Description = "Generated by EFCore.SchemaSync from the EF Core model. Do not edit.",
        };

        try
        {
            DacPackageExtensions.BuildPackage(stream, model, metadata, new PackageOptions());
        }
        catch (DacServicesException ex)
        {
            throw new SchemaSyncException(SchemaSyncStage.BuildPackage, "DacFx could not build the DACPAC: " + Flatten(ex.Message), ex);
        }

        return new SchemaPackage(packageName, stream.ToArray(), objects, warnings, script.ToScript(), script.SkippedSeedStatements);
    }

    private static string Format(DacModelMessage message)
        => $"{message.Prefix}{message.Number}: {message.Message}";

    private static string Flatten(string message) => message.Replace("\r", string.Empty).Replace('\n', ' ').Trim();
}
