<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\EFCore.SchemaSync.Tests\Models\*.cs" Link="Models\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" Version="13.6.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.5.1" />
    <PackageReference Include="MSTest.TestFramework" Version="4.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EFCore.SchemaSync\EFCore.SchemaSync.csproj" />
    <ProjectReference Include="..\..\samples\SchemaSync.Sample\SchemaSync.Sample.csproj" />
    <ProjectReference Include="..\EFCore.SchemaSync.IntegrationTests.AppHost\EFCore.SchemaSync.IntegrationTests.AppHost.csproj" />
  </ItemGroup>

</Project>
